### ISSUE TITLE
Exact filtering in FILTER column

### ISSUE THREAD

**Issue by kokyriakidis** [vembrane/vembrane#105]
Hi!
I tried to filter a vcf with vembrane but it lacks EXACT matching filtering. It always keeps subsets. 

**For example I want to keep both `clustered_events` and `clustered_events;slippage`. Only those tags.** 

If I write `"clustered_events" in FILTER or "clustered_events;slippage" in FILTER` vembrane keeps both of them plus many stand alone tags like `slippage`, `"clustered_events;base_qual"` etc.

My workaround is to exclude all tags that I do not want to get subsets. like:

```
vembrane filter '"haplotype" not in FILTER and "map_qual" not in FILTER and "base_qual" not in FILTER and "multiallelic" not in FILTER and "strand_bias" not in FILTER and "weak_evidence" not in FILTER and "strict_strand" not in FILTER and "possible_numt" not in FILTER and "position" not in FILTER and "orientation" not in FILTER and "FAIL" not in FILTER and "duplicate" not in FILTER and "MinAF" not in FILTER'
```
and then use bcftools which has exact filtering capabilities to filter the `slippage` tag BUT keeping `clustered_events;slippage`

Can you have a look at it?

**Comment by kokyriakidis** [comment]
Thanks for the info! I will try it out!

**Comment by kokyriakidis** [comment]
HI @tedil !

It would also be great to have the ability to write the output to a gz file format. Moreover it would be great if there was an option to create the index of the output.

**Comment by tedil** [comment]
Please open a new issue if the topic is a new one!

(Also, both suggestions are out of scope of vembrane's intended functionality. You can easily (b)gzip the files using other tools, same goes for building an index.
E.g. with pipes `vembrane filter "some expression" input.vcf | gzip -c > output.vcf.gz`.)

Did my previous answer solve your initial problem? If so, I can close this issue ;)
