### ISSUE TITLE
Recognize CSQ as ANN

### ISSUE THREAD

**Issue by wwgordon** [vembrane/vembrane#149]
Would it be possible to have a CSQ field recognized in the same manner as an ANN field? Many VEP annotated VCFs use this label rather than ANN as it is the default behavior:

> Change the name of the INFO key that VEP write the consequences to in its [VCF output](https://useast.ensembl.org/info/docs/tools/vep/vep_formats.html#vcfout). Use "ANN" for compatibility with other tools such as [snpEff](http://snpeff.sourceforge.net/). Default: CSQ

**Comment by christopher-schroeder** [comment]
As far as I know, this is already the case. If you set the name for the annotation key with ```--annotation-key ANN``` it should work as described. Do you have any problems doing so?
Best
Christo

**Comment by wwgordon** [comment]
You are correct, my apologies, I was misinterpreting that option.

**Comment by christopher-schroeder** [comment]
No need to apologize. It means that the text is written not clear enough. We will improve the writing. Thank you!
