### ISSUE TITLE
v1.0.2 aux option is broken

### ISSUE THREAD

**Issue by ptrebert** [vembrane/vembrane#150]
Hi,
when running the following command, I get a NameError:

```
vembrane filter --aux chroms=main_chroms.tsv 'CHROM in AUX["chroms"] and "PASS" in FILTER' input.vcf.gz
```

```
Traceback (most recent call last):
  File "/usr/local/bin/vembrane", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/vembrane/cli.py", line 23, in main
    filter.execute(args)
  File "/usr/local/lib/python3.10/site-packages/vembrane/modules/filter.py", line 352, in execute
    first_record = list(islice(records, 1))
  File "/usr/local/lib/python3.10/site-packages/vembrane/modules/filter.py", line 199, in filter_vcf
    record, keep = test_and_update_record(
  File "/usr/local/lib/python3.10/site-packages/vembrane/modules/filter.py", line 162, in test_and_update_record
    return record, env.evaluate()
  File "/usr/local/lib/python3.10/site-packages/vembrane/representations.py", line 390, in evaluate
    return self._func()
  File "<string>", line 1, in <lambda>
NameError: name 'chroms' is not defined
```

The file `main_chroms.tsv` contains one chromosome name per line, if relevant.

Best,
Peter

**Comment by christopher-schroeder** [comment]
Hey Peter,
i've just tested this and for me it works. Which version are you using? Would you mind pasting the content of "main_chroms.tsv"?

**Comment by ptrebert** [comment]
The version: `vembrane_v1.0.2_pyhdfd78af_0.sif`

The file content:
```
chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr21
chr22
chrX
```

**Comment by christopher-schroeder** [comment]
Thank you, I have no problem. The result is as expected in my test. Would you test the command on your side with this test data?

https://raw.githubusercontent.com/vembrane/vembrane/main/tests/testcases/test01/test.vcf

Just to make sure its not the data, that is somehow broken.

**Comment by ptrebert** [comment]
I get the same error with the test vcf you provided.

However, I debugged this myself: I am executing `vembrane` as a singularity container (see my second message), creating a conda environment with `vembrane` does not result in the error. Using the container, the command line has to be adapted like this:

```
vembrane filter --aux chroms=main_chroms.tsv 'CHROM in AUX[\"chroms\"] and \"PASS\" in FILTER' test.vcf 
```

I don't know which part now mandates the escaping of the double quotes, so it's either something to improve in `vembrane` or a caveat to add to the documentation.

**Comment by christopher-schroeder** [comment]
Great! I saw you are using singularity, but my knowledge about it is limited, so I don't really know whats going on here with the quotes. Maybe someone else knows more about this.

**Comment by tedil** [comment]
> I get the same error with the test vcf you provided.
> 
> However, I debugged this myself: I am executing `vembrane` as a singularity container (see my second message), creating a conda environment with `vembrane` does not result in the error. Using the container, the command line has to be adapted like this:
> 
> ```
> vembrane filter --aux chroms=main_chroms.tsv 'CHROM in AUX[\"chroms\"] and \"PASS\" in FILTER' test.vcf 
> ```
> 
> I don't know which part now mandates the escaping of the double quotes, so it's either something to improve in `vembrane` or a caveat to add to the documentation.

I also have no experience using singularity. Could it also be shell related?
Does swapping single and double quotes change anything?
```sh
vembrane filter --aux chroms=main_chroms.tsv "CHROM in AUX['chroms'] and 'PASS' in FILTER" test.vcf 
```

**Comment by tedil** [comment]
@ptrebert any news on this?
