### ISSUE TITLE
filter based on fulfilling two out of five conditions 

### ISSUE THREAD

**Issue by zihhuafang** [vembrane/vembrane#182]
Hi!

Thanks for developing vembrane.
I have a question regarding to the expression to use for filtering for the variants that fulfill two out of five conditions (just an example) using VEP annotation.

For example, I set 5 conditions as below:
CADD_PHRED > 25
REVEL_score > 0.5
VARITY_R_score > 0.8
VEST4_score > 0.5
am_pathogenicity > 0.6

Any variant fulfills two of out 5 conditions will be kept.

Example annotation for VEP:
`##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|MANE_SELECT|MANE_PLUS_CLINICAL|TSL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|UNIPROT_ISOFORM|SOURCE|GENE_PHENO|NEAREST|SIFT|PolyPhen|DOMAINS|miRNA|HGVS_OFFSET|gnomADe_AF|gnomADe_AFR_AF|gnomADe_AMR_AF|gnomADe_ASJ_AF|gnomADe_EAS_AF|gnomADe_FIN_AF|gnomADe_NFE_AF|gnomADe_OTH_AF|gnomADe_SAS_AF|gnomADg_AF|gnomADg_AFR_AF|gnomADg_AMI_AF|gnomADg_AMR_AF|gnomADg_ASJ_AF|gnomADg_EAS_AF|gnomADg_FIN_AF|gnomADg_MID_AF|gnomADg_NFE_AF|gnomADg_OTH_AF|gnomADg_SAS_AF|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|PUBMED|VAR_SYNONYMS|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|TRANSCRIPTION_FACTORS|EVE_CLASS|EVE_SCORE|am_class|am_pathogenicity|SpliceVault_SpliceAI_delta|SpliceVault_out_of_frame_events|SpliceVault_site_max_depth|SpliceVault_site_pos|SpliceVault_site_sample_count|SpliceVault_site_type|SpliceVault_top_events|existing_InFrame_oORFs|existing_OutOfFrame_oORFs|existing_uORFs|five_prime_UTR_variant_annotation|five_prime_UTR_variant_consequence|TSSDistance|NMD|DownstreamProtein|ProteinLengthChange|CADD_PHRED|CADD_RAW|DisGeNET|BayesDel_noAF_score|FATHMM_score|GERP++_RS|GTEx_V8_sQTL_gene|GTEx_V8_sQTL_tissue|MPC_score|MetaRNN_score|MutPred_score|REVEL_score|VARITY_R_score|VEST4_score|fathmm-MKL_coding_score|LoF|LoF_filter|LoF_flags|LoF_info|SpliceAI_pred_DP_AG|SpliceAI_pred_DP_AL|SpliceAI_pred_DP_DG|SpliceAI_pred_DP_DL|SpliceAI_pred_DS_AG|SpliceAI_pred_DS_AL|SpliceAI_pred_DS_DG|SpliceAI_pred_DS_DL|SpliceAI_pred_SYMBOL|ClinVar|ClinVar_CLNSIG|ClinVar_|ClinVar_CLNDN|PAI3D|PAI3D_PAI3D">`

Example vcf record:
`chr21	15864349	chr21_15864349_G_A	G	A	36	PASS	AF=3.1e-05;AQ=36;AN=16568;AC=0;AC_Hom=0;CSQ=A|missense_variant|MODERATE|USP25|ENSG00000155313|Transcript|ENST00000400183|protein_coding|21/26||ENST00000400183.7:c.2629G>A|ENSP00000383044.2:p.Val877Ile|3041|2629|877|V/I|Gta/Ata|rs1465330225||1||SNV|HGNC|HGNC:12624|YES|NM_001283041.3||1|A1|CCDS63336.1|ENSP00000383044|Q9UHP3.204||UPI000040FA6E|Q9UHP3-3|||USP25|tolerated_low_confidence(0.48)|benign(0.309)|CDD:cd20486|||3.983e-06|0|2.896e-05|0|0|0|0|0|0||||||||||||2.896e-05|gnomADe_AMR|||||||||||||||||||||||||||||||21.6|2.303592||-0.549033|1.8|5.62||||0.15876132||0.076||0.182|0.95856|||||21|-11|-17|-1|0.00|0.00|0.00|0.00|USP25|||||chr21:15864349-15864349|0.3770209871977567`

I wonder if this would be possible because any() or all() won't work here?
Thanks!
Zih-Hua

**Comment by tedil** [comment]
Assuming you want _at least 2 out of 5_ and not _exactly 2 out of 5_, the following might work:
```py
sum([CSQ["CADD_PHRED"] > 25, CSQ["REVEL_score > 0.5"] > 0.5, CSQ["VARITY_R_score"]  > 0.8,  CSQ["VEST4_score"]  > 0.5, CSQ["am_pathogenicity"]  > 0.6]) >= 2
```
This makes use of the fact that boolean `False` can be interpreted as integer `0` and boolean `True` as integer `1`.

I think vembrane does not type the scores you use correctly yet, so the values will be of type `str`, not `int`/`float`.
To ensure you have the right types, cast to the respective type, e.g. `float(CSQ["VARITY_R_score"])`.

**Comment by zihhuafang** [comment]
Hi,
Thanks again for the example.

The logic works well, but I'm running into an issue where some of the annotation fields are empty, causing vembrane to raise the ValueError: could not convert string to float: NoValue().

According to README, I thought when annotation field lacks a value, it will be replaced with the special value of NA?
Using the variant in the example above where "am_pathogenicity" is missing with the following code:
`vembrane filter --annotation-key CSQ 'float(CSQ["am_pathogenicity"]) > 0.5' test.vcf`

I got the ValueError:
```
Traceback (most recent call last):
  File "/opt/conda/bin/vembrane", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/vembrane/cli.py", line 23, in main
    filter.execute(args)
  File "/opt/conda/lib/python3.10/site-packages/vembrane/modules/filter.py", line 365, in execute
    first_record = list(islice(records, 1))
  File "/opt/conda/lib/python3.10/site-packages/vembrane/modules/filter.py", line 212, in filter_vcf
    record, keep = test_and_update_record(
  File "/opt/conda/lib/python3.10/site-packages/vembrane/modules/filter.py", line 150, in test_and_update_record
    filtered_annotations = [
  File "/opt/conda/lib/python3.10/site-packages/vembrane/modules/filter.py", line 151, in <listcomp>
    annotation for annotation in annotations if env.evaluate(annotation)
  File "/opt/conda/lib/python3.10/site-packages/vembrane/representations.py", line 390, in evaluate
    return self._func()
  File "<string>", line 1, in <lambda>
ValueError: could not convert string to float: NoValue()
```

I split the vep annotation by bcftools +split-vep with the same variant to confirm am_pathogenicity is indeed missing:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr21	15864349	chr21_15864349_G_A	G	A	36	PASS	AF=3.1e-05;AQ=36;AN=16568;AC=0;AC_Hom=0;CSQ=A|missense_variant|MODERATE|USP25|ENSG00000155313|Transcript|ENST00000400183|protein_coding|21/26||ENST00000400183.7:c.2629G>A|ENSP00000383044.2:p.Val877Ile|3041|2629|877|V/I|Gta/Ata|rs1465330225||1||SNV|HGNC|HGNC:12624|YES|NM_001283041.3||1|A1|CCDS63336.1|ENSP00000383044|Q9UHP3.204||UPI000040FA6E|Q9UHP3-3|||USP25|tolerated_low_confidence(0.48)|benign(0.309)|CDD:cd20486|||3.983e-06|0|2.896e-05|0|0|0|0|0|0||||||||||||2.896e-05|gnomADe_AMR|||||||||||||||||||||||||||||||21.6|2.303592||-0.549033|1.8|5.62||||0.15876132||0.076||0.182|0.95856|||||21|-11|-17|-1|0.00|0.00|0.00|0.00|USP25|||||chr21:15864349-15864349|0.3770209871977567;Cases_cohort=0,1,1;Controls_cohort=0,0,0;CC_TREND_cohort=0.4983;CC_GENO_cohort=nan;CC_ALL_cohort=0.6857;CC_DOM_cohort=0.6857;CC_REC_cohort=1;TOPMed8_AF=-1;TOPMed8_AC=-1;TOPMed8_nhet=-1;TOPMed8_nhomalt=-1;gnomADg_AF=-1;gnomADg_nhomalt=-1;gnomAD_joint_nhomalt=-1;gnomADg_Popmax_AF=-1;gnomAD_Popmax_joint_AF=-1;gnomADg_AC=-1;impactful;genic;highest_impact_order=14;MAF=0;BIOTYPE=protein_coding;SYMBOL=USP25;IMPACT=MODERATE;LoF=.;CADD_PHRED=21.6;SpliceAI_pred_DS_AG=0;SpliceAI_pred_DS_AL=0;SpliceAI_pred_DS_DG=0;SpliceAI_pred_DS_DL=0;VEST4_score=0.182;REVEL_score=0.076;BayesDel_noAF_score=-0.549033;PAI3D_PAI3D=0.377021;am_pathogenicity=.;Consequence=missense_variant
```

I tried with `vembrane filter --annotation-key CSQ 'float(CSQ["REVEL_score"]) > 0.5' test.vcf` where REVEL_score was available with a value as shown above and did not run into the same error.

Is there anything I am missing?
Thanks a lot for the advice!

**Comment by tedil** [comment]
So `float(CSQ["am_pathogenicity"])` translates to `float(NA)` which is indeed not a valid conversion. I have to think about whether adding those makes sense or not.

For the time being, you can try e.g.:
 -  `float(CSQ["am_pathogenicity"] or "-inf") > 0.5` (to get a negative infinity for the comparison instead) 
 - `(NA if (amp := CSQ["am_pathogenicity"]) is NA else float(amp)) > 0.5` (to get a NA value for comparison again, which should be safer)

**Comment by zihhuafang** [comment]
Thanks a lot for the example code again! 
I tried the second solution, and it worked regardless of the available annotations.
I don't think it's possible to add all the annotations, but this solution is elegant and versatile for all possible ones.

Thanks again!
