### ISSUE TITLE
GT 1/1 Error

### ISSUE THREAD

**Issue by christopher-schroeder** [vembrane/vembrane#99]
There seems to be an error, when the genotype is 1/1, 0|1 or similar. vembrane thinks these are 2 values instead of one single string.

**Comment by tedil** [comment]
That's because it's never a single string, that's just the representation. pysam stores these as an n-tuple of int or None, e.g. in the triploid case `0/1/.` is stored as `(0, 1, None)`.

**Comment by christopher-schroeder** [comment]
Even if the vcf header define the type as string?

**Comment by tedil** [comment]
Yes, even if the header defines this as string!
